id: ABD4D0EA2
title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the Liberational
  Life of the Omniscient Jamyang Khyentse Wangpo'
type: translation
pechas:
- I4173AC92
- I9F3102A1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:04.480018
  last_modified_at: 2023-01-04 12:36:04.480026
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I4173AC92/81BB: EA62
  I9F3102A1/111C: EA62
